import logging
from typing import Dict, Any, List
from fastapi import APIRouter, Header, HTTPException, Depends

from backend.marketing_os_app.auth.rbac import RBAC
from backend.marketing_os_app.api_gateway.router import authenticate_tenant
from backend.marketing_os_app.feature_flags.feature_manager import FeatureManager

feature_engine = FeatureManager()

logger = logging.getLogger(__name__)

admin_router = APIRouter()

@admin_router.post("/api/v1/admin/toggle-shadow-mode")
async def override_shadow_mode(enable: bool, context: Dict[str, str] = Depends(authenticate_tenant)):
    """
    Client manually forces or releases the Autonomous constraints globally.
    Requires ADMIN or OWNER.
    """
    role = context["role"]
    cid = context["company_id"]
    
    # 1. Access Check
    RBAC.enforce_role(role, "ADMIN")
    
    # 2. Audit Trail
    logger.info(f"AUDIT TRAIL: Tenant {cid} - Role {role} manually toggled Shadow Mode to {enable}")
    
    # 3. Mocks hitting Core GenesisEngine to update state
    # engine._safe_update(cid, "constraints", {"shadow_mode_enabled": enable}, "Client SaaS", "Manual Override")
    
    return {"status": "success", "shadow_mode_active": enable, "message": "Global Governance array updated successfully."}

@admin_router.post("/api/v1/admin/approve-calibration")
async def approve_tuning(parameter_name: str, requested_value: float, context: Dict[str, str] = Depends(authenticate_tenant)):
    """
    Accepts the backtested statistical mapping generated by the Calibration Core.
    """
    role = context["role"]
    cid = context["company_id"]
    system_mode = context["system_mode"]
    
    if not feature_engine.can_approve_calibration(system_mode, role):
        logger.error(f"AUDIT TRAIL: Tenant {cid} - Role {role} with mode {system_mode} attempted unauthorized calibration approval.")
        raise HTTPException(status_code=403, detail="Your system mode or role does not permit manual calibration approvals.")
        
    RBAC.enforce_role(role, "ADMIN")
    logger.info(f"AUDIT TRAIL: Tenant {cid} - Tuning {parameter_name} to {requested_value} approved.")
    
    # Normally resolves the ParameterSuggestion DB entry returning True to Genesis
    
    return {"status": "success", "message": f"Tuning boundary for {parameter_name} mapped into Liquid constraints successfully."}
