import os
import logging
from typing import Dict, Any, List
from datetime import datetime

logger = logging.getLogger(__name__)

class CampaignExecutor:
    """
    Handles autonomous or manual execution of campaign actions.
    Simulates talking to the Platform Integration Service.
    """
    
    def __init__(self):
        # In a real scenario, this would interface with PlatformIntegration / RabbitMQ
        self.active_executions = {}
        
    def execute_adjustments(self, business_id: str, decisions: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Parses rules generated by the Intelligence Layer and pushes API commands.
        """
        applied_logs = []
        
        # 1. Budget Changes
        scale_factor = decisions.get("budget_scaling_factor", 1.0)
        suggested_budget = decisions.get("suggested_budget")
        action = decisions.get("recommended_action")
        
        if scale_factor != 1.0:
            log_msg = f"API CMD: Adjusted budget to ${suggested_budget} ({action}, scale={scale_factor})"
            logger.info(log_msg)
            applied_logs.append({"action": "budget_update", "detail": log_msg})
            
        # 2. Creative Pausing
        should_replace = decisions.get("should_replace_creative", False)
        if should_replace:
            reason = decisions.get("creative_replace_reason", "Underperforming")
            log_msg = f"API CMD: Paused active creative. Reason: {reason}"
            logger.info(log_msg)
            applied_logs.append({"action": "creative_paused", "detail": log_msg})
            
        # 3. LLM Strategy Injection (New ad variations)
        strategy = decisions.get("llm_strategy")
        if strategy and "No strategy" not in strategy:
            log_msg = f"API CMD: Generated new campaign variant based on strategy map."
            logger.info(log_msg)
            applied_logs.append({"action": "variant_creation", "detail": log_msg, "strategy_preview": strategy[:100]})
            
        if not applied_logs:
            applied_logs.append({"action": "none", "detail": "No changes required. Holding."})
            
        return applied_logs

    def pause_all_campaigns(self, business_id: str) -> bool:
        """
        Fires KILL_SWITCH signal immediately.
        """
        logger.critical(f"EMERGENCY KILL SWITCH ACTIVATED FOR BIZ: {business_id}. SHUTTING DOWN ALL CAMPAIGNS.")
        return True
