"""
Multi-Agent Strategy Council Models
===================================
Structures for agent insights, proposed actions, and inter-agent debate records.
"""

from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

import enum

class AgentRole(str, enum.Enum):
    GROWTH     = "growth_agent"
    CREATIVE   = "creative_agent"
    MARKET     = "market_agent"
    COMPETITOR = "competitor_agent"
    RISK       = "risk_agent"


class ActionProposal(BaseModel):
    """Specific executable proposal submitted by an agent."""
    action_type: str
    target: str
    rationale: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    expected_cpa_delta: float = 0.0


class AgentInsight(BaseModel):
    """Output from an individual strategy agent."""
    agent_role: AgentRole
    observations: List[str]
    proposed_actions: List[ActionProposal]
    confidence_score: float = Field(ge=0.0, le=1.0)
    risk_level: str = "medium"


class DebateInteraction(BaseModel):
    """A challenge or support generated during the Debate Phase."""
    source_agent: AgentRole
    target_agent: AgentRole
    interaction_type: str  # support, challenge, refine
    rationale: str
    proposed_adjustment: Optional[Dict[str, Any]] = None


class CouncilSynthesis(BaseModel):
    """The final fused output generated by the Synthesis Engine."""
    opportunity_summary: str
    threat_summary: str
    final_actions: List[ActionProposal]
    overall_confidence: float
    expected_cpa_change: float
    debate_summary: List[str]
