"""
CaptainStrategy — Data Models
=============================
Defines the output strategy objects generated by the Captain Brain.
"""

import uuid
import enum
from datetime import datetime, timezone
from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, JSON, Text
from sqlalchemy.orm import declarative_base

Base = declarative_base()

def _uuid(): return str(uuid.uuid4())


class StrategyStatus(str, enum.Enum):
    PENDING_SIMULATION = "pending_simulation"
    PENDING_APPROVAL   = "pending_approval"
    APPROVED           = "approved"
    REJECTED           = "rejected"
    EXECUTING          = "executing"
    COMPLETED          = "completed"
    FAILED             = "failed"


class ActionType(str, enum.Enum):
    SCALE_BUDGET       = "scale_budget"
    REDUCE_BUDGET      = "reduce_budget"
    PAUSE_CAMPAIGN     = "pause_campaign"
    NEW_CREATIVE_ANGLE = "new_creative_angle"
    AUDIENCE_EXPANSION = "audience_expansion"
    PLATFORM_SHIFT     = "platform_shift"
    BID_ADJUSTMENT     = "bid_adjustment"
    OFFER_CHANGE       = "offer_change"


class RecommendedAction(Base):
    """Specific executable command generated by CaptainStrategy."""
    __tablename__ = "captain_actions"

    id               = Column(String, primary_key=True, default=_uuid)
    strategy_id      = Column(String, index=True, nullable=False)
    action_type      = Column(String, nullable=False)
    target_entity_id = Column(String, nullable=True)   # campaign_id, adset_id, etc.
    platform         = Column(String, nullable=True)   # meta, google, tiktok
    
    # Execution detail
    payload          = Column(JSON, nullable=False)    # e.g., {"budget_increase_pct": 15}
    rationale        = Column(Text, nullable=True)
    
    # Predicted outcomes for this specific action
    expected_cpa_delta= Column(Float, nullable=True)
    expected_ctr_delta= Column(Float, nullable=True)
    expected_roas_delta= Column(Float, nullable=True)
    
    status           = Column(String, default="pending")
    created_at       = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class GeneratedStrategy(Base):
    """Full strategic plan generated by CaptainStrategy."""
    __tablename__ = "captain_strategies"

    id               = Column(String, primary_key=True, default=_uuid)
    company_id       = Column(String, index=True, nullable=False)
    
    # 1. Perception & Understanding Inputs used to generate this
    fused_context    = Column(JSON, nullable=False)  # Snapshot of reality
    
    # 2. Detected Forces
    opportunities    = Column(JSON, nullable=False)  # List of opportunity dicts
    threats          = Column(JSON, nullable=False)  # List of threat dicts
    
    # 3. Decision Outputs
    narrative        = Column(Text, nullable=True)   # AI-generated strategy brief
    confidence_score = Column(Float, nullable=False, default=0.0)
    risk_score       = Column(Float, nullable=False, default=0.0)
    
    # Predicted global outcomes for the strategy
    predicted_lift   = Column(Float, nullable=True)
    predicted_cpa_change = Column(Float, nullable=True)
    
    # Workflow
    status           = Column(String, default=StrategyStatus.PENDING_SIMULATION)
    execution_mode   = Column(String, default="manual") # manual vs autonomous
    
    # Learning Loop fields (filled later)
    actual_lift      = Column(Float, nullable=True)
    actual_cpa_change= Column(Float, nullable=True)
    learning_delta   = Column(Float, nullable=True)  # How wrong the prediction was
    
    created_at       = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at       = Column(DateTime, default=lambda: datetime.now(timezone.utc))
